@startuml Code level for 4.1.2

class OperationPlanRoute {
    +createOperationPlan(req, res, next)
    +updateOperationPlan( req, res, next)
    +getAllOperationPlans(req, res, next)
    +getOperationPlanById( req, res, next)
    +getOperationPlansByVvn(req, res, next)
    +getOperationPlansByTargetDay(req, res, next)
    +getOperationPlansByAuthor(req, res, next)
    +getOperationPlansByAlgorithm(req, res, next)
}

interface IOperationPlanController{
    +getAllOperationPlans(req, res, next)
    +getOperationPlanById(req, res, next)
    +getOperationPlansByVvn(req, res, next)
    +getOperationPlansByTargetDay(req, res, next)
    +getOperationPlansByArrivalTime(req, res, next)
    +getOperationPlansByDepartureTime(req, res, next)
    +getOperationPlansByAuthor(req, res, next)
    +getOperationPlansByAlgorithm(req, res, next)
    +createOperationPlan(req, res, next)
    +updateOperationPlan(req, res, next)
}

class OperationPlanController {
    +getAllOperationPlans(req, res, next)
    +getOperationPlanById(req, res, next)
    +getOperationPlansByVvn(req, res, next)
    +getOperationPlansByTargetDay(req, res, next)
    +getOperationPlansByArrivalTime(req, res, next)
    +getOperationPlansByDepartureTime(req, res, next)
    +getOperationPlansByAuthor(req, res, next)
    +getOperationPlansByAlgorithm(req, res, next)
    +createOperationPlan(req, res, next)
    +updateOperationPlan(req, res, next)
}

class OperationPlanService {
    +getAllOperationPlans()
    +getOperationPlanById(id: string)
    +getOperationPlansByVvn(vvn: string)
    +getOperationPlansByTargetDay(targetDay: Date)
    +getOperationPlansByArrivalTime(arrivalTime: Date)
    +getOperationPlansByDepartureTime(departureTime: Date)
    +getOperationPlansByAuthor(author: string)
    +getOperationPlansByAlgorithm(algorithm: string)
    +create(dto: OperationPlanDTO)
    +update(vvn: string, dto: OperationPlanDTO)
    +createOperationEntries(vvn: string,assignedCranes: string[],operationTypes: string[],\ncontainers: string[],arrivalTime: Date,departureTime: Date)
    +createBatch(vvns: string[],assignedCranes: string[][],staffs: string[][],operationTypes: string[][]\n,containers: string[][],arrivalTimes: string[],departureTimes: string[],targetDays: string[],author: string,algorithm: string)
}

interface IOperationPlanService{
    +getAllIncidentTypes()
    +getIncidentTypeById(id: string)
    +getIncidentTypeByCode(code: string)
    +getIncidentTypeByName(name: string)
    +getIncidentTypesWithParent(hasParent: boolean)
    +getIncidentTypesByClassification(classification: string)
    +getIncidentTypesByParent(parentCode: string)
    +create(dto: IncidentTypeDTO)
    +update(code: string,dto: IncidentTypeDTO)
}

interface IOperationPlanRepo {
    +findAll()
    +findById(id: string)
    +findByVvn(vvn: string)
    +findByTargetDay(targetDay: Date)
    +findByArrivalTime(arrivalTime: Date)
    +findByDepartureTime(departureTime: Date)
    +findByAuthor(author: string)
    +findByAlgorithm(algorithm: string)
    +update(operationPlan: OperationPlan)
    +findByIds(ids: string[])
}

class OperationPlanRepo {
    +exists(plan: OperationPlan)
    +save(plan: OperationPlan)
    +findByIds(ids: string[])
    +findAll()
    +findById(id: string)
    +findByVvn(vvn: string)
    +findByTargetDay(targetDay: Date)
    +findByArrivalTime(arrivalTime: Date)
    +findByDepartureTime(departureTime: Date)
    +findByAuthor(author: string)
    +findByAlgorithm(algorithm: string)
    +update(plan: OperationPlan)
}

class OperationPlanDTO {
    -id: string
    -vvn: string
    -targetDay: Date
    -arrivalTime: Date
    -departureTime: Date
    -operations: OperationEntryDTO[]
    -author: string
    -algorithm: string
    -createdAt: Date
}

class OperationEntryDTO {
    -id: string
    -operationType: string
    -container: string
    -operationStart: Date
    -operationEnd: Date
    -craneUsed: string
}

class OperationPlanMap {
    +toDomain(raw: IOperationPlanPersistence | any)
    +toPersistence(plan: OperationPlan)
    +toDTO(plan: OperationPlan)
}

class OperationEntryMap {
    +toDomain(raw: IOperationEntryPersistence | any)
    +toPersistence(entry: OperationEntry)
    +toDTO(entry: OperationEntry)
}

class OperationPlan {
    -id: string
    -code: string
    -name: string
    -description: string
    -classification: IncidentClassification
    -parentIncidentTypeId?: string
}

class OperationEntry {
    -id: string
    -operationType: string
    -container: string
    -operationStart: Date
    -operationEnd: Date
    -craneUsed: string
}



interface IOperationPlanPersistence {
    -_id: string
    -vvn: string
    -TargetDay: Date
    -arrivalTime: Date
    -departureTime: Date
    -operations: IOperationEntryPersistence[]
    -author: string
    -algorithm: string
    -createdAt: Date
}

interface IOperationEntryPersistence {
    -_id: string
    -operationType: string
    -container: string
    -operationStart: Date
    -operationEnd: Date
    -craneUsed: string
}

class OperationPlanSchema {
    +mongooseModel: Model
}

class MongoDBCluster <<database>>

OperationPlanRoute --> OperationPlanController : forwards requests
OperationPlanController ..|> IOperationPlanController
OperationPlanController --> OperationPlanService : invokes methods
OperationPlanService --> OperationPlanDTO : consumes/produces
OperationPlanService --> OperationPlanMap : delegates mapping
OperationPlanService ---> IOperationPlanRepo : uses persistence abstraction
OperationPlanService .up.|> IOperationPlanService

OperationPlanRepo ..|> IOperationPlanRepo
OperationPlanRepo --> OperationPlanMap : uses
OperationPlanRepo --> OperationPlanSchema : uses ODM
OperationPlanSchema --> IOperationPlanPersistence : implements structure
OperationPlanSchema --> MongoDBCluster : stores documents

OperationPlanMap --> OperationPlan : maps domain
OperationPlanMap --> OperationPlanDTO : maps DTO
OperationPlanMap --> IOperationPlanPersistence : maps persistence

OperationPlan --> OperationEntry : aggregates
OperationEntryMap --> OperationEntry : maps domain
OperationPlanMap --> OperationEntryMap : uses for entries
OperationEntryMap --> IOperationEntryPersistence : maps persistence
OperationEntryMap --> OperationEntryDTO : maps DTO
IOperationPlanPersistence --> IOperationEntryPersistence : contains
@enduml