@startuml 4.1.14
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Port Operation Supervisor" as portOpSupervisor
participant "UI" as ui
participant "System" as system

title System Sequence Diagram - US4.1.13

== Manage Catalog of Complementary Task Categories ==
activate portOpSupervisor

portOpSupervisor -> ui: Manage Complementary Task Categories\n(Create, Read, Update)
activate ui
ui -> portOpSupervisor : Request Complementary Task Categories Data
deactivate ui

portOpSupervisor -> ui : Provide Complementary Task Categories Data
activate ui
ui -> system : Invoke Complementary Task Categories Management System
activate system

system -> system : Process Complementary Task Categories Data

system --> ui : Return Operation Result
deactivate system
ui -> portOpSupervisor : Display Operation Result
deactivate ui 



@enduml
