version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5432:5432"
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.2
    container_name: keycloak
    command: start --import-realm --spi-import-export-strategy=IGNORE_EXISTING
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: 141.253.198.138
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: "none"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./export:/opt/keycloak/data/import
      - keycloak-data-vol:/opt/keycloak/data

volumes:
  keycloak-data:
  keycloak-data-vol:
