@startuml us2.2.8_vesselvisit_update
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

actor "Shipping Agent Representative" as representative
participant "VesselVisitNotification Controller" as VVNController
participant "VesselVisitNotification Service" as VVNService
participant "VesselVisitNotificationDTO" as VVNDTO
participant "VesselVisitNotification Factory" as VVNFactory
participant "CargoManifest" as CargoManifest
participant "Container" as Container
participant "CargoManifestEntry" as CargoManifestEntry
participant "VesselVisitNotification" as VVNDomain
participant "VesselVisitNotification Repository" as VVNRepository
participant "VesselVisitNotification Mapper" as VVNMapper
participant "VesselRecord Repository" as VesselRecordRepository
participant "VesselRecord Mapper" as VesselRecordMapper
participant "Representative Repository" as RepresentativeRepository
participant "Representative Mapper" as RepresentativeMapper
participant "StorageArea Repository" as StorageAreaRepository
participant "StorageArea Mapper" as StorageAreaMapper
participant "ShippingManagementContext" as DbContext
participant "ShippingManagementDatabase" as Database

title System Sequence Diagram - PUT VesselVisitNotification (US2.2.9)

activate representative
	representative -> VVNController: PUT /api/VesselVisitNotification/Update/{visitCode} (VesselVisitNotificationDTO)
	activate VVNController

		VVNController -> VVNService: UpdateVesselVisitNotification(visitCode, vesselVisitNotificationDTO, _errorMessages)
		activate VVNService
			VVNService -> VVNRepository: GetVisitByCodeAsync(dto.Code)
			activate VVNRepository
				VVNRepository -> DbContext: Set<VesselVisitNotificationDataModel>().Include(vvn => vvn.Vessel)!.ThenInclude(v => v.VesselType)\n.Include(vvn => vvn.Representative)!.ThenInclude(r => r.Organization)\n.Include(vvn => vvn.CargoManifests)!.ThenInclude(cm => cm.Entries)\n.ThenInclude(e => e.StorageArea).Include(vvn => vvn.CrewMembers)!.FirstOrDefaultAsync(vvn => vvn.Code == visitCode)
				activate DbContext
					DbContext --> Database: SELECT * FROM VesselVisitNotifications WHERE Code = @code
					activate Database
					Database --> DbContext: VesselVisitNotificationDataModel? (found/null)
					deactivate Database
					DbContext --> VVNRepository: VesselVisitNotificationDataModel? (found/null)
				deactivate DbContext
                VVNRepository -> VVNMapper: ToDomain(vesselVisitDM)
                        activate VVNMapper
                            VVNMapper --> VVNRepository: VesselVisitNotification (domain)
                    deactivate VVNMapper    
				alt not found
					VVNRepository --> VVNService: null
					VVNService -> VVNController: return null + ["Vessel Visit Notification not found."]
				else
                    VVNRepository -> VVNService: VesselVisitNotification (domain)
				end
			deactivate VVNRepository
			VVNService -> VVNRepository: GetVisitsByVesselIMOAsync(dto.VesselIMO)
			activate VVNRepository
				VVNRepository -> DbContext: Set<VesselVisitNotificationDataModel>().Include(vvn => vvn.Vessel)!.ThenInclude(v => v.VesselType)\n.Include(vvn => vvn.Representative)!.ThenInclude(r => r.Organization)\n.Include(vvn => vvn.CargoManifests)!.ThenInclude(cm => cm.Entries)\n.ThenInclude(e => e.StorageArea).Include(vvn => vvn.CrewMembers)!\n.Where(vvn => vvn.Vessel!.IMONumber == imoNumber).ToListAsync()
				activate DbContext
					DbContext --> Database: SELECT * FROM VesselVisitNotifications WHERE Vessel_IMONumber = @imo
					activate Database
					Database --> DbContext: List<VesselVisitNotificationDataModel>
					deactivate Database
					DbContext --> VVNRepository: List<VesselVisitNotificationDataModel>
				deactivate DbContext
                VVNRepository --> VVNMapper: ToDomain(vesselVisitDMs)
                        activate VVNMapper
                            VVNMapper --> VVNRepository: List<VesselVisitNotification> (domain)
                    deactivate VVNMapper
				VVNRepository --> VVNService: visits (list)
			deactivate VVNRepository
			alt overlapping visits
				VVNService -> VVNController: return null + ["There is an overlapping visit for the same vessel."]
			end

			VVNService -> VesselRecordRepository: GetVesselRecordByImoNumberAsync(dto.VesselIMO)
			activate VesselRecordRepository
				VesselRecordRepository -> DbContext: Set<VesselRecordDataModel>().Include(v => v.VesselType).SingleOrDefaultAsync(v => v.IMONumber == imoNumber);
				activate DbContext
					DbContext --> Database: SELECT * FROM VesselRecords WHERE IMONumber = @imo
					activate Database
					Database --> DbContext: VesselRecordDataModel? (found/null)
					deactivate Database
					DbContext --> VesselRecordRepository: VesselRecordDataModel? (found/null)
				deactivate DbContext
                    VesselRecordRepository -> VesselRecordMapper: ToDomain(VesselRecordDataModel)
                    activate VesselRecordMapper
                        VesselRecordMapper --> VesselRecordRepository: VesselRecord (domain)
                    deactivate VesselRecordMapper
				alt found
					VesselRecordRepository -> VVNService: VesselRecord (domain)
				else
					VesselRecordRepository --> VVNService: null
				end
			deactivate VesselRecordRepository

			VVNService -> RepresentativeRepository: GetRepresentativeByCitizenIdAsync(dto.RepresentativeCitizenID)
			activate RepresentativeRepository
				RepresentativeRepository -> DbContext:Set<RepresentativeDataModel>().Include(r => r.Organization).SingleOrDefaultAsync(r => r.CitizenId == citizenId)
				activate DbContext
					DbContext --> Database: SELECT * FROM Representatives WHERE CitizenId = @citizenId
					activate Database
					Database --> DbContext: RepresentativeDataModel? (found/null)
					deactivate Database
					DbContext --> RepresentativeRepository: RepresentativeDataModel? (found/null)
				deactivate DbContext
                RepresentativeRepository -> RepresentativeMapper: ToDomain(RepresentativeDataModel)
                activate RepresentativeMapper
                    RepresentativeMapper --> RepresentativeRepository: Representative (domain)
                deactivate RepresentativeMapper
				alt found
					RepresentativeRepository -> VVNService: Representative (domain)
				else
					RepresentativeRepository --> VVNService: null
				end
			deactivate RepresentativeRepository

            VVNService -> VVNService: ConvertCrewMemberDTOsToCrewMembers(notificationDTO.CrewMembers)

			VVNService -> VVNDomain: ChangeVessel(vessel)
                activate VVNDomain
                    VVNDomain --> VVNService: 
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeRepresentative(representative)
                activate VVNDomain
                    VVNDomain --> VVNService: 
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeETAETD(notificationDTO.Eta, notificationDTO.Etd)
                activate VVNDomain
                    VVNDomain --> VVNService: 
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeNumberOfCrewMembers(notificationDTO.NumberOfCrewMembers)
                activate VVNDomain
                    VVNDomain --> VVNService: 
                deactivate VVNDomain


			loop for each cargoManifestDTO in dto.CargoManifests
				VVNService -> CargoManifest: <<create>> new CargoManifest(cmDto.ManifestType, new List<CargoManifestEntry>(), vesselVisitNotification)
                    activate CargoManifest
                        CargoManifest --> VVNService: CargoManifest (domain)
                    deactivate CargoManifest
				loop for each entryDTO in cargoManifestDTO.Entries
                    VVNService -> Container: <<create>> Container(entryDto.ContainerNumber)
                        activate Container
                            Container --> VVNService: Container (domain)
                        deactivate Container
					VVNService -> StorageAreaRepository: GetStorageAreaByCodeAsync(entryDTO.StorageAreaCode)
					activate StorageAreaRepository
						StorageAreaRepository -> DbContext: Set<StorageAreaDataModel>().Include(sa => sa.StorageAreaDocks)!.ThenInclude(sad => sad.Dock)!.FirstOrDefaultAsync(sa => sa.Code == code)
						activate DbContext
							DbContext --> Database: SELECT * FROM StorageAreas WHERE Code = @code
							activate Database
							Database --> DbContext: StorageAreaDataModel? (found/null)
							deactivate Database
							DbContext --> StorageAreaRepository: StorageAreaDataModel? (found/null)
						deactivate DbContext
                        StorageAreaRepository -> StorageAreaMapper: ToDomain(StorageAreaDataModel)
                        activate StorageAreaMapper
                            StorageAreaMapper --> StorageAreaRepository: storageArea (domain)
                        deactivate StorageAreaMapper
						alt found
							StorageAreaRepository -> VVNService: StorageArea (domain)
						else
							StorageAreaRepository --> VVNService: null
						end
					deactivate StorageAreaRepository

					alt storage area missing
						VVNService -> VVNController: return null + ["Storage area not found"]
					else
						VVNService -> CargoManifestEntry: <<create>> CargoManifestEntry(container, entryDto.Row, entryDto.Bay, entryDto.Tier, storageArea, manifest)
                            activate CargoManifestEntry
                                CargoManifestEntry --> VVNService: CargoManifestEntry (domain)
                            deactivate CargoManifestEntry
					end
				end
			end

			VVNService -> VVNDomain: ChangeCargoManifests(cargoManifests)
                activate VVNDomain
                    VVNDomain --> VVNService: 
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeCargoType(notificationDTO.CargoType)
                activate VVNDomain
                    VVNDomain --> VVNService: 
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeVolume(notificationDTO.Volume)
                activate VVNDomain
                    VVNDomain --> VVNService:
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeCrewMembers(crewMembers)
                activate VVNDomain
                    VVNDomain --> VVNService:
                deactivate VVNDomain
            VVNService -> VVNDomain: ChangeVisitStatus(notificationDTO.VisitStatus)
                activate VVNDomain
                    VVNDomain --> VVNService:
                deactivate VVNDomain
            
			VVNService -> VVNRepository: UpdateVisitAsync(existingNotification, errorMessages)
			activate VVNRepository
				
                VVNRepository -> DbContext: Set<VesselVisitNotificationDataModel>().Include(vvn => vvn.Vessel).ThenInclude(v => v.VesselType)\n.Include(vvn => vvn.Representative).ThenInclude(r => r.Organization)\n.Include(vvn => vvn.CargoManifests)!.ThenInclude(cm => cm.Entries)\n.ThenInclude(e => e.StorageArea).Include(vvn => vvn.CrewMembers)!\n.FirstOrDefaultAsync(vvn => vvn.Id == notification.Id)
                    activate DbContext  
                        DbContext --> Database: SELECT * FROM VesselVisitNotifications WHERE Id = @id
                        activate Database
                        Database --> DbContext: VesselVisitNotificationDataModel? (found/null)
                        deactivate Database
                        DbContext --> VVNRepository: VesselVisitNotificationDataModel? (found/null)
                    deactivate DbContext
                VVNRepository --> VVNMapper : UpdateDataModelAsync(dm, notification, _context)
                    activate VVNMapper
                        VVNMapper --> VVNRepository: 
                    deactivate VVNMapper
				VVNRepository -> DbContext: SaveChangesAsync()
                    activate DbContext
                        DbContext --> Database: UPDATE VesselVistitNotification ... and join table updates
                        activate Database
                        Database --> DbContext: Commit/Success
                        deactivate Database
                        DbContext --> VVNRepository:
                    deactivate DbContext
			    VVNRepository --> VVNService: true
			deactivate VVNRepository
			VVNService --> VVNController: true
		deactivate VVNService

		alt success
            VVNController --> representative: 200 OK
        else validation error
            VVNController --> representative: 400 Bad Request (errorMessages)
        else conflict
            VVNController --> representative: 404 Not Found (errorMessages)
        end
	deactivate VVNController
deactivate representative

@enduml

