// <auto-generated />
using System;
using DataModel.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataModel.Migrations
{
    [DbContext(typeof(ShippingManagementContext))]
    [Migration("20251210174407_AddLastAcceptedPrivacyPolicyAtToSystemUsers")]
    partial class AddLastAcceptedPrivacyPolicyAtToSystemUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DataModel.Model.CargoManifestDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<long>("VesselVisitNotificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("CargoManifests");
                });

            modelBuilder.Entity("DataModel.Model.CargoManifestEntryDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Bay")
                        .HasColumnType("int");

                    b.Property<long>("CargoManifestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Container")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<long>("StorageAreaId")
                        .HasColumnType("bigint");

                    b.Property<int>("Tier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CargoManifestId");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("CargoManifestEntries");
                });

            modelBuilder.Entity("DataModel.Model.CrewMemberDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("VesselVisitNotificationDataModelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationDataModelId");

                    b.ToTable("CrewMembers");
                });

            modelBuilder.Entity("DataModel.Model.DecisionDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OfficerId")
                        .HasColumnType("bigint");

                    b.Property<string>("ResponseMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("VesselVisitNotificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("Decision", (string)null);
                });

            modelBuilder.Entity("DataModel.Model.DockDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaxDraft")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Location")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Docks");
                });

            modelBuilder.Entity("DataModel.Model.DockReassignmentLogDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("OfficerId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OriginalDockId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UpdatedDockId")
                        .HasColumnType("bigint");

                    b.Property<long>("VesselVisitNotificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OriginalDockId");

                    b.HasIndex("UpdatedDockId");

                    b.HasIndex("VesselVisitNotificationId");

                    b.ToTable("DockReassignmentLogDataModel");
                });

            modelBuilder.Entity("DataModel.Model.PhysicalResourceDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedDockName")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AssignedStorageAreaCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("EndDay")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("OperationalCapacity")
                        .HasColumnType("int");

                    b.Property<int?>("SetupTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int>("StartDay")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhysicalResources");
                });

            modelBuilder.Entity("DataModel.Model.PrivacyPolicyDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("PrivacyPolicies");
                });

            modelBuilder.Entity("DataModel.Model.QualificationDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("DataModel.Model.RepresentativeDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CitizenId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("Representatives");
                });

            modelBuilder.Entity("DataModel.Model.ShippingAgentOrganizationDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AlternativeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Address")
                        .IsUnique();

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("LegalName")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.ToTable("ShippingAgentOrganizations");
                });

            modelBuilder.Entity("DataModel.Model.StaffDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("DataModel.Model.StorageAreaDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CurrentCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Location")
                        .IsUnique();

                    b.ToTable("StorageAreas");
                });

            modelBuilder.Entity("DataModel.Model.StorageAreaDockDataModel", b =>
                {
                    b.Property<long>("StorageAreaId")
                        .HasColumnType("bigint");

                    b.Property<long>("DockId")
                        .HasColumnType("bigint");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.HasKey("StorageAreaId", "DockId");

                    b.HasIndex("DockId");

                    b.ToTable("StorageAreaDock", (string)null);
                });

            modelBuilder.Entity("DataModel.Model.SystemUserDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsFirstTime")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastAcceptedPrivacyPolicyAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("DataModel.Model.VesselRecordDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("IMONumber")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("VesselTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IMONumber")
                        .IsUnique();

                    b.HasIndex("VesselName");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("VesselRecords");
                });

            modelBuilder.Entity("DataModel.Model.VesselTypeDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaxBays")
                        .HasColumnType("int");

                    b.Property<int>("MaxRows")
                        .HasColumnType("int");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VesselTypes");
                });

            modelBuilder.Entity("DataModel.Model.VesselVisitNotificationDataModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AssignedDockId")
                        .HasColumnType("bigint");

                    b.Property<string>("CargoType")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ETA")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ETD")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfCrewMembers")
                        .HasColumnType("int");

                    b.Property<long>("RepresentativeId")
                        .HasColumnType("bigint");

                    b.Property<long>("VesselId")
                        .HasColumnType("bigint");

                    b.Property<string>("VisitStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Volume")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AssignedDockId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RepresentativeId");

                    b.HasIndex("VesselId");

                    b.ToTable("VesselVisitNotification", (string)null);
                });

            modelBuilder.Entity("DockDataModelVesselTypeDataModel", b =>
                {
                    b.Property<long>("DockDataModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("VesselTypesAllowedId")
                        .HasColumnType("bigint");

                    b.HasKey("DockDataModelId", "VesselTypesAllowedId");

                    b.HasIndex("VesselTypesAllowedId");

                    b.ToTable("DockVesselTypeAllowed", (string)null);
                });

            modelBuilder.Entity("PhysicalResourceDataModelQualificationDataModel", b =>
                {
                    b.Property<long>("PhysicalResourceDataModelId")
                        .HasColumnType("bigint");

                    b.Property<long>("QualificationRequirementsId")
                        .HasColumnType("bigint");

                    b.HasKey("PhysicalResourceDataModelId", "QualificationRequirementsId");

                    b.HasIndex("QualificationRequirementsId");

                    b.ToTable("PhysicalResourceQualifications", (string)null);
                });

            modelBuilder.Entity("QualificationDataModelStaffDataModel", b =>
                {
                    b.Property<long>("QualificationId")
                        .HasColumnType("bigint");

                    b.Property<long>("StaffDataModelId")
                        .HasColumnType("bigint");

                    b.HasKey("QualificationId", "StaffDataModelId");

                    b.HasIndex("StaffDataModelId");

                    b.ToTable("StaffQualification", (string)null);
                });

            modelBuilder.Entity("DataModel.Model.CargoManifestDataModel", b =>
                {
                    b.HasOne("DataModel.Model.VesselVisitNotificationDataModel", "VesselVisitNotification")
                        .WithMany("CargoManifests")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselVisitNotification");
                });

            modelBuilder.Entity("DataModel.Model.CargoManifestEntryDataModel", b =>
                {
                    b.HasOne("DataModel.Model.CargoManifestDataModel", "CargoManifest")
                        .WithMany("Entries")
                        .HasForeignKey("CargoManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.StorageAreaDataModel", "StorageArea")
                        .WithMany()
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoManifest");

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("DataModel.Model.CrewMemberDataModel", b =>
                {
                    b.HasOne("DataModel.Model.VesselVisitNotificationDataModel", null)
                        .WithMany("CrewMembers")
                        .HasForeignKey("VesselVisitNotificationDataModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Model.DecisionDataModel", b =>
                {
                    b.HasOne("DataModel.Model.VesselVisitNotificationDataModel", "VesselVisitNotification")
                        .WithMany()
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselVisitNotification");
                });

            modelBuilder.Entity("DataModel.Model.DockReassignmentLogDataModel", b =>
                {
                    b.HasOne("DataModel.Model.DockDataModel", "OriginalDock")
                        .WithMany()
                        .HasForeignKey("OriginalDockId");

                    b.HasOne("DataModel.Model.DockDataModel", "UpdatedDock")
                        .WithMany()
                        .HasForeignKey("UpdatedDockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.VesselVisitNotificationDataModel", "VesselVisitNotification")
                        .WithMany("DockReassignmentLogs")
                        .HasForeignKey("VesselVisitNotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalDock");

                    b.Navigation("UpdatedDock");

                    b.Navigation("VesselVisitNotification");
                });

            modelBuilder.Entity("DataModel.Model.RepresentativeDataModel", b =>
                {
                    b.HasOne("DataModel.Model.ShippingAgentOrganizationDataModel", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("DataModel.Model.StaffDataModel", b =>
                {
                    b.OwnsOne("Domain.Model.OperationalWindow", "OperationalWindow", b1 =>
                        {
                            b1.Property<long>("StaffDataModelId")
                                .HasColumnType("bigint");

                            b1.Property<int>("EndDay")
                                .HasColumnType("int")
                                .HasColumnName("OperationalWindow_EndDay");

                            b1.Property<TimeSpan>("EndTime")
                                .HasColumnType("time(6)")
                                .HasColumnName("OperationalWindow_EndTime");

                            b1.Property<int>("StartDay")
                                .HasColumnType("int")
                                .HasColumnName("OperationalWindow_StartDay");

                            b1.Property<TimeSpan>("StartTime")
                                .HasColumnType("time(6)")
                                .HasColumnName("OperationalWindow_StartTime");

                            b1.HasKey("StaffDataModelId");

                            b1.ToTable("Staffs");

                            b1.WithOwner()
                                .HasForeignKey("StaffDataModelId");
                        });

                    b.Navigation("OperationalWindow")
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.Model.StorageAreaDockDataModel", b =>
                {
                    b.HasOne("DataModel.Model.DockDataModel", "Dock")
                        .WithMany()
                        .HasForeignKey("DockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.StorageAreaDataModel", "StorageArea")
                        .WithMany("StorageAreaDocks")
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dock");

                    b.Navigation("StorageArea");
                });

            modelBuilder.Entity("DataModel.Model.VesselRecordDataModel", b =>
                {
                    b.HasOne("DataModel.Model.VesselTypeDataModel", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselType");
                });

            modelBuilder.Entity("DataModel.Model.VesselVisitNotificationDataModel", b =>
                {
                    b.HasOne("DataModel.Model.DockDataModel", "AssignedDock")
                        .WithMany()
                        .HasForeignKey("AssignedDockId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataModel.Model.RepresentativeDataModel", "Representative")
                        .WithMany()
                        .HasForeignKey("RepresentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.VesselRecordDataModel", "Vessel")
                        .WithMany()
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedDock");

                    b.Navigation("Representative");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("DockDataModelVesselTypeDataModel", b =>
                {
                    b.HasOne("DataModel.Model.DockDataModel", null)
                        .WithMany()
                        .HasForeignKey("DockDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.VesselTypeDataModel", null)
                        .WithMany()
                        .HasForeignKey("VesselTypesAllowedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PhysicalResourceDataModelQualificationDataModel", b =>
                {
                    b.HasOne("DataModel.Model.PhysicalResourceDataModel", null)
                        .WithMany()
                        .HasForeignKey("PhysicalResourceDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.QualificationDataModel", null)
                        .WithMany()
                        .HasForeignKey("QualificationRequirementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QualificationDataModelStaffDataModel", b =>
                {
                    b.HasOne("DataModel.Model.QualificationDataModel", null)
                        .WithMany()
                        .HasForeignKey("QualificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataModel.Model.StaffDataModel", null)
                        .WithMany()
                        .HasForeignKey("StaffDataModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataModel.Model.CargoManifestDataModel", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DataModel.Model.StorageAreaDataModel", b =>
                {
                    b.Navigation("StorageAreaDocks");
                });

            modelBuilder.Entity("DataModel.Model.VesselVisitNotificationDataModel", b =>
                {
                    b.Navigation("CargoManifests");

                    b.Navigation("CrewMembers");

                    b.Navigation("DockReassignmentLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
